//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestField
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmotionDBEntities : DbContext
    {
        public EmotionDBEntities()
            : base("name=EmotionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<OwnedItem> OwnedItems { get; set; }
        public virtual DbSet<UserData> UserDatas { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
