//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameworkClasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int UserId { get; set; }
        public int JoyCoins { get; set; }
        public int JoyGems { get; set; }
        public short DailyStreak { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> Anger { get; set; }
        public Nullable<int> Contempt { get; set; }
        public Nullable<int> Disgust { get; set; }
        public Nullable<int> Fear { get; set; }
        public Nullable<int> Happiness { get; set; }
        public Nullable<int> Neutral { get; set; }
        public Nullable<int> Sadness { get; set; }
        public Nullable<int> Surprise { get; set; }
    
        public virtual User User { get; set; }
    }
}
