CREATE TABLE [dbo].[OwnedItems]
(
	[Id] INT NOT NULL PRIMARY KEY,
	[UserId] INT NOT NULL, 
	[ItemId] INT NOT NULL, 
	[ItemCount] INT NOT NULL, 
    CONSTRAINT [FK_UserId_ToUsers1] FOREIGN KEY ([UserId]) REFERENCES [Users]([Id]) ON DELETE CASCADE ON UPDATE CASCADE, 
    CONSTRAINT [FK_ItemId_ToItems1] FOREIGN KEY ([ItemId]) REFERENCES [Items]([Id]) ON DELETE CASCADE ON UPDATE CASCADE 
)
